name: Build Blogpost from Issue

on:
  issues:
    types: [opened, edited, labeled, reopened]

permissions:
  contents: write
  issues: write

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'blogpost')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse Issue and write Markdown + HTML
        id: gen
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require("fs");
            const path = require("path");

            const body = context.payload.issue.body || "";

            function val(label){
              const re = new RegExp(`^###\\s+${label.replace(/[.*+?^${}()|[\\]\\\\]/g,"\\$&")}\\s*\\n([\\s\\S]*?)(?=\\n^###\\s+|$)`, "im");
              const m = body.match(re);
              return m ? m[1].trim() : "";
            }
            function valAny(labels){
              for (const L of labels){
                const v = val(L);
                if (v) return v;
              }
              return "";
            }
            function valLastSection(){
              const parts = body.split(/\n(?=###\s+)/);
              return parts.length ? parts[parts.length-1].replace(/^###\s+[^\n]+\n/i,"").trim() : "";
            }

            const title      = valAny(["Titel"]);
            const slugManual = valAny(["Slug (optional)","Slug"]);
            const tagsRaw    = valAny(["Tags (Komma-getrennt, klein, ohne Leerzeichen)","Tags"]);
            const cover      = valAny(["Cover-Bild-URL (optional)","Cover"]);
            const excerpt    = valAny(["Kurz-Teaser (max. 240 Zeichen)","Kurz-Teaser","Teaser"]);
            const metaTitle  = valAny(["Meta Title (optional)","Meta Title"]);
            const metaDesc   = valAny(["Meta Description (optional)","Meta Description"]);

            let bodymd = valAny(["Artikel (Markdown)","Artikel","Content","Inhalt"]);
            if (!bodymd) bodymd = valLastSection();
            bodymd = bodymd.replace(/^```[a-z]*\n?/i,'').replace(/\n```$/,'').trim();

            if (!title)  core.setFailed("Titel fehlt.");
            if (!bodymd) core.setFailed("Artikel (Markdown) fehlt.");

            const tags = (tagsRaw || "").split(",").map(s=>s.trim()).filter(Boolean);

            function slugify(s){
              return s.toLowerCase()
                .normalize("NFKD").replace(/[\u0300-\u036f]/g,"")
                .replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80);
            }

            const created = new Date(context.payload.issue.created_at);
            const y = created.getUTCFullYear();
            const m = String(created.getUTCMonth()+1).padStart(2,'0');
            const d = String(created.getUTCDate()).padStart(2,'0');
            const date = `${y}-${m}-${d}`;

            const slug = slugManual ? slugify(slugManual) : slugify(title);
            const fileName = `${date}-${slug}.md`;
            const repoPath = "blog/posts";                          // <— ohne "finalfinal"
            const fullPath = path.join(process.cwd(), repoPath, fileName);

            const lines = ["---"];
            lines.push(`title: ${JSON.stringify(title)}`);
            lines.push(`date: ${date}`);
            lines.push(`tags: [${tags.join(", ")}]`);
            if (cover)     lines.push(`cover: ${JSON.stringify(cover)}`);
            if (excerpt)   lines.push(`excerpt: ${JSON.stringify(excerpt)}`);
            if (metaTitle) lines.push(`metaTitle: ${JSON.stringify(metaTitle)}`);
            if (metaDesc)  lines.push(`metaDescription: ${JSON.stringify(metaDesc)}`);
            lines.push("---", "", bodymd, "");

            fs.mkdirSync(path.join(process.cwd(), repoPath), { recursive: true });
            fs.writeFileSync(fullPath, lines.join("\n"));

            // Markdown -> HTML via GitHub API
            const rendered = await github.rest.markdown.render({
              text: bodymd,
              mode: "gfm"
            });

            const html = `<!doctype html><html lang="de">
<head>
<meta charset="utf-8">
<title>${metaTitle ? metaTitle : title} — Blog</title>
<meta name="description" content=${JSON.stringify(metaDesc || excerpt || "")}>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="canonical" href="https://zukunftsberatung.xyz/blog/posts/${fileName.replace(/\\.md$/, ".html")}">
<meta property="og:title" content=${JSON.stringify(metaTitle || title)}>
<meta property="og:description" content=${JSON.stringify(metaDesc || excerpt || "")}>
${cover ? `<meta property="og:image" content=${JSON.stringify(cover)}>` : ""}
<meta property="og:type" content="article">
<meta property="article:published_time" content="${date}">
<script type="application/ld+json">
${JSON.stringify({
  "@context":"https://schema.org",
  "@type":"Article",
  "headline": title,
  "datePublished": date,
  "image": cover || undefined,
  "keywords": (tags||[]).join(", ")
})}
</script>
<link rel="stylesheet" href="/assets/mobirise/css/mbr-additional.css">
</head>
<body>
<main class="container" style="max-width:900px;margin:2rem auto;padding:1rem">
<h1>${title}</h1>
<p><time datetime="${date}">${date}</time>${tags.length?` · ${tags.map(t=>`#${t}`).join(" ")}`:""}</p>
${cover?`<p><img src=${JSON.stringify(cover)} alt=${JSON.stringify(title)} style="max-width:100%;height:auto"></p>`:""}
${rendered.data}
</main>
</body></html>`;

            const htmlPath = fullPath.replace(/\\.md$/, ".html");
            fs.writeFileSync(htmlPath, html);

            core.setOutput("file", `${repoPath}/${fileName}`);
            core.setOutput("html", `${repoPath}/${fileName.replace(/\\.md$/, ".html")}`);
            core.setOutput("slug", slug);
            core.setOutput("date", date);

      - name: Commit and push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add blog/posts/*.md blog/posts/*.html
          git commit -m "blog: add ${{ steps.gen.outputs.file }}" || echo "no changes"
          git push

      - name: Comment with links and close
        uses: actions/github-script@v7
        with:
          script: |
            const file = `${{ toJSON(steps.gen.outputs.file) }}`;
            const html = `${{ toJSON(steps.gen.outputs.html) }}`;
            const repo = `${context.repo.owner}/${context.repo.repo}`;
            const urlMd  = `https://github.com/${repo}/blob/main/${file}`;
            const live   = `https://zukunftsberatung.xyz/blog/posts/${html.split("/").pop()}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Erstellt: ${urlMd}\nLive: ${live}`
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: "closed"
            });
