name: Publish Blog Markdown to HTML

on:
  push:
    paths:
      - '**/blog/posts/*.md'
  workflow_dispatch:
  workflow_run:
    workflows: [blogpost.yml]  # exakt wie in Actions angezeigt
    types: [completed]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Find changed markdown files
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            mapfile -t files < <(git ls-files '**/blog/posts/*.md')
          else
            mapfile -t files < <(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**/blog/posts/*.md')
          fi
          echo "count=${#files[@]}" >> $GITHUB_OUTPUT
          printf '%s\0' "${files[@]}" > md-files.txt || true

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert MD to HTML
        if: steps.diff.outputs.count != '0'
        shell: bash
        run: |
          mkdir -p finalfinal/blog/posts
          while IFS= read -r -d '' file; do
            base="$(basename "$file" .md)"
            out="finalfinal/blog/posts/${base}.html"
            pandoc "$file" -f markdown -t html5 -s -o "$out"
            echo "Generated $out"
          done < md-files.txt

      - name: Commit and push HTML
        if: steps.diff.outputs.count != '0'
        run: |
          git add finalfinal/blog/posts/*.html
          git commit -m "blog: publish HTML from MD"
          git push origin HEAD
